### ISSUE TITLE
Build with vs2017 got LNK2038 error

### ISSUE THREAD

**Issue by Match-Yang** [openbigdatagroup/vivecinema#1]
Hello.
I was trying to build this project with vs2017 and then I got the LNK2038 error.
I figure it out that the balai_vs2012.lib was builded by vs2012 witch can not be link with vs2017 build.
So, can i get the source of balai or can you offer the lib file build by vs2017?
Thanks!

**Comment by andrechen** [comment]
Thank you. i'll put vs2017 libs with later update, after fully test CUDA and GL interoperability.

**Comment by Match-Yang** [comment]
That is great!Thanks!

**Comment by andrechen** [comment]
vs2017 binaries pushed. enjoy~
