### ISSUE TITLE
3OA+HL arranged it two Streams to play on VIVE

### ISSUE THREAD

**Issue by aeqm** [openbigdatagroup/vivecinema#2]
I'm having issues trying to play a .mov video which has two streams of audio mapped with ffmpeg: 3OA and Head Locked stereo on Vive Cinema on a Oculus Rift DK2 and Windows 10 PC.
I know the two streams exist as I open the file on VLC and first track is the 3OA, second track is the stereo file but when played on VIVE the stereo doesn´t play.  What can I possibly be doing wrong?

I very much appreciate any help

**Comment by andrechen** [comment]
if no metadata is embedded in your mov, you must play it in 360 mode to active ambisonics decoder + headlock stereo. but you must select 360 mode before playing. If it's already playing, try switching video mode to 360 and back to menu then play it again.

It should work as we have lots of such videos. But if it's not working, send me your short demo clip, so i can help you?

P.S. If you're using vive cinema downloaded from viewport, be sure to update the .exe here.

thank you,
andre.hl.chen@gmail.com

**Comment by aeqm** [comment]
thanks for the reply. Metadata is done through Spatial Media Metadata Injector. Nevertheless the case "My video has spatial audio" is greyed out but the output video still has two streams of audio as tested in VLC.  My video shows as marked 360 in the main panel. I'm afraid I don't have a external controller for the Oculus Rift DK2 so I play the video with spacebar within the Vive app and the only possible other action is switching between videos with arrows. Few hours back, the VIVE app updated itself. I do have a vive.exe file in VIVE/PCClient folder , is that the one you recommend to be update? I sure can send you a short demo clip but it is 139MB size, shall I wetransfer it to you? Many thanks again indeed

**Comment by andrechen** [comment]
For some reasons, we don't release the latest update on viveport any longer. please use the binary as below link. You can simply run the app directly, viveport is not required. now it's version 1.1.938.

I've checked your video, and yes, i heard both BGM (head lock) and spatial audio (16-channel 3OA). 

https://github.com/openbigdatagroup/vivecinema/tree/master/vivecinema/bin

**Comment by andrechen** [comment]
Of course, you can just replace the ViveCinema.exe in your viveport app path and use viveport launcher as before.

**Comment by aeqm** [comment]
Thanks a lot Andre, this actually solved this issue and some others I was having when playing 3OA. One more question, the player's volume setting by default is set to maximum volume? I don't have a way to know as don't have acces to this menu because of lack of controller. I feel my soundmix is playing quietly than normal, can you confirm? And again thanks for such an amazing app

**Comment by andrechen** [comment]
yes, it plays maximum volume. the only way to control the volume is to adjust system volume settings.
