### ISSUE TITLE
playing an mp4 that has no .mp4 extension

### ISSUE THREAD

**Issue by vmacavero** [openbigdatagroup/vivecinema#3]
Hi, i have a 360 mp4 file. It is correctly played, but only when it  has the .mp4 extension. 
If i rename it and has no extension, i can't play it, neither if i give him some other extension like .vr360 (for example).

Is there a way to force the program to play the files (as a regular mp4 ? )

I tried forcing in xml config file with no luck.

Should i compile the program again on myself ?  But what option my i change to make it recognize the "vr360" extension and threat it like a normal mp4 ?

Thanks

**Comment by andrechen** [comment]
Hi, you can modify the [code](https://github.com/openbigdatagroup/vivecinema/blob/master/vivecinema/VRVideoPlayer.cpp#L2290) to support the .vr360 file extension. But to specify the 360 videos, it's more common to have normal .mp4 or .mov file extensions with [metadata](https://github.com/google/spatial-media) built-in.

Thanks.
